function textbox = popupWhite(input, fig)
% Function popupStroop displays a pop-up message in a figure.
% (By Lisa Thelen and Lizzy Da Rocha Bazilio)

message = sprintf(input);
textbox = annotation(fig, 'textbox',...
    'String', message,...
    'color', [1 1 1],'FontSize', 20,...
    'Position',[.3 .3 .4 .4],...
    'HorizontalAlignment', 'center',...
    'VerticalAlignment', 'middle',...
    'EdgeColor', [1 1 1]);
end 

